name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run -r build

      - name: Deploy
        run: pnpm deploy --filter=webapp --prod ./build

      - name: Set version based on head_ref when pull or ref_name when tag.
        if: github.event_name ==  'push' && startsWith(github.ref, 'refs/tags/')
        run: echo "EDITOR_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Set version based on head_ref when pull or ref_name when tag.
        if: github.event_name == 'pull_request'
        run: echo "EDITOR_VERSION=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Fixup
        run: |
          find build/ -type f -exec sed -i -e 's,="/assets,="assets,' -e 's,="/favicon,="favicon,' {} \;
          sed -i -e "s,%version%,${{ env.EDITOR_VERSION }}," build/dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dist
          publish_branch: gh-pages-new  # don't overwrite the existing gh-pages branch.
          destination_dir: ${{ env.EDITOR_VERSION }}
